# DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/outboxdb}
quarkus.datasource.username=${DB_USER:outbox}
quarkus.datasource.password=${DB_PASSWORD:outbox}

# JPA + Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

# API docs + health
quarkus.swagger-ui.always-include=true

# Email sender
quarkus.mailer.host=${MAIL_HOST:localhost}
quarkus.mailer.port=${MAIL_PORT:1025}
quarkus.mailer.start-tls=DISABLED
quarkus.mailer.mock=${MAIL_MOCK:false}
app.mail.from=${MAIL_FROM:no-reply@outboxsample.local}
app.activation.base-url=${APP_BASE_URL:http://localhost:8080}

# Outbox dispatcher
outbox.dispatch.every=${OUTBOX_DISPATCH_EVERY:10s}
outbox.dispatch.batch-size=${OUTBOX_DISPATCH_BATCH_SIZE:20}
outbox.dispatch.max-attempts=${OUTBOX_DISPATCH_MAX_ATTEMPTS:5}
outbox.dispatch.retry-delay-seconds=${OUTBOX_DISPATCH_RETRY_DELAY_SECONDS:30}

# Test profile
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:outbox;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.scheduler.enabled=false
%test.quarkus.mailer.mock=true
